# Generated by Django 5.2.4 on 2025-07-28 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.SlugField(unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('wilaya', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('founded_at', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='club_logos/')),
                ('departments', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_requests', to=settings.AUTH_USER_MODEL)),
                ('vice_president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
