# Generated by Django 5.2.4 on 2025-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrequest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
